services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=posts_ms_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - 'data:/data'
  rabbitmq:
    image: 'rabbitmq:3.12.7-management-alpine'
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
volumes:
  data: {}
networks:
  default:
    name: 'socialsync_network'
