services:
  mongodb-posts:
    container_name: 'mongodb_posts'
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=posts_ms_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - 'data:/data'
  mongodb-comments:
    container_name: 'mongodb_comments'
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=comments_ms_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27018:27017'
    expose:
      - '27018'
    volumes:
      - 'data2:/data2'
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'data3:/data3'
  rabbitmq:
    image: 'rabbitmq:3.12.7-management-alpine'
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - '5672'
      - '15672'
volumes:
  data: {}
  data2: {}
  data3: {}
networks:
  default:
    name: 'socialsync_network'
