services:
  mongodb-topics:
    container_name: 'mongodb_topics'
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=posts_ms_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27019:27017'
    expose:
      - '27019'
    volumes:
      - 'data3:/data3'
      
  mongodb-posts:
    container_name: 'mongodb_posts'
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=posts_ms_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - 'data:/data'
  
  mongodb-notif:
    container_name: 'mongodb_notif'
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=notif_ms_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27020:27017'
    expose:
      - '27017'
    volumes:
      - 'data:/data'
      
  mongodb-comments:
    container_name: 'mongodb_comments'
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=comments_ms_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27018:27017'
    expose:
      - '27018'
    volumes:
      - 'data2:/data2'

  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'data3:/data3'

  redis-query:
    image: 'redis/redis-stack:latest'
    environment:
      - 'REDIS_ARGS=--appendonly yes'
    container_name: 'redis-query'
    ports:
      - '6379:6379'
      - '8001:8001'
    expose:
      - '6379'
      - '8001'

  rabbitmq:
    image: 'rabbitmq:3.12.7-management-alpine'
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - '5672'
      - '15672'

  users-microservice:
    build: "./users-microservice"
    image: "users-ms:v1"
    container_name: "users-microservice"
    depends_on:
      - rabbitmq
      - mariadb
    ports:
      - '8082:8082'
    expose:
      - '8082'

  topics-microservice:
    build: "./topics-microservice"
    image: "topics-ms:v1"
    container_name: "topics-microservice"
    depends_on:
      - rabbitmq
      - mongodb-topics
      - users-microservice
    ports:
      - '8084:8084'
    expose:
      - '8084'

  posts-microservice:
    build: "./posts-microservice"
    image: "posts-ms:v1"
    container_name: "posts-microservice"
    depends_on:
      - rabbitmq
      - mongodb-posts
      - users-microservice
      - topics-microservice
    ports:
      - '8080:8080'
    expose:
      - '8080'

  comments-microservice:
    build: "./comments-microservice"
    image: "comments-ms:v1"
    container_name: "comments-microservice"
    depends_on:
      - rabbitmq
      - mongodb-comments
      - users-microservice
      - posts-microservice
    ports:
      - '8081:8081'
    expose:
      - '8081'
      
  authorization-microservice:
    build: "./authorization-microservice"
    image: "authorization-ms:v1"
    container_name: "authorization-microservice"
    ports:
      - '8087:8087'
    expose:
      - '8087'

# nu mai e in docker
#  gateway:
#    build: "./gateway"
#    image: "gateway-ms:v1"
#    container_name: "gateway"
#    ports:
#      - '8086:8086'
#    expose:
#      - '8086'

  storage-microservice:
    build: "./storage-microservice"
    image: 'storage-ms:v1'
    container_name: "storage-microservice"
    ports:
      - '8088:8088'
    expose:
      - '8088'
    volumes:
      - 'storage:/storage'

  notify-microservice:
    build: "./notify-microservice"
    image: "notify-ms:v1"
    container_name: "notify-microservice"
    depends_on:
      - rabbitmq
      - mongodb-posts
    ports:
      - '8090:8090'
    expose:
      - '8090'

# simulare d3 de la aws
  minio-simulator:
    image: minio/minio
    container_name: minio-simulator
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    ports:
      - "8091:9000"
    volumes:
      - minio-data:/data
    command: server /data
    networks:
      - default

volumes:
  data: {}
  data1: {}
  data2: {}
  data3: {}
  storage: {}
  minio-data: {}

networks:
  default:
    name: 'socialsync_network'
